### ISSUE TITLE
Speaker name extraction doesn't consider more than one word.

### ISSUE THREAD

**Issue by saurabhshri** [saurabhshri/simple-yet-powerful-srt-subtitle-parser-cpp#1]
In case of single-word speaker name, the parser works fine, but in case there are more than one word, only last word is extracted.

`Saurabh: Oompa Loompa` is extracted as `Oompa Loompa`, while
`Saurabh Shri: Oompa Loompa` is extracted as `Saurabh Oompa Loompa`.

This is just a matter of searching till the start of statement / appearance of "\n".

**Comment by saurabhshri** [comment]
Resolved in https://github.com/saurabhshri/simple-yet-powerful-srt-subtitle-parser-cpp/commit/3f3e2a3bfd33495c2e36eec3dacac2e21cb41006 .

**Comment by Jonathhhan** [comment]
I have a similar issue. For example `getDialogue()` `MAN 1: Looks like a tie.` becomes `MAN: Looks like a tie.` and it should become `Looks like a tie.`. And `BLANEY: Rusk did it.` doesnt change and should become: `Rusk did it.` And somehow your pull request above gives me a dublicate symbols error message. It would be great, if that is possible to fix.

**Comment by Jonathhhan** [comment]
Another thing that I experienced is that the subtitle text: `Mr. Rusk.` becomes `   Mr. Rusk.`.
